In [ ]:
# https://www.youtube.com/watch?v=HPjBY1H-U4U&list=PLhhyoLH6IjfxVOdVC1P1L5z5azs0XjMsb&index=2
# tf intro

import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'


In [30]:
#  ініціалізація тензорів
x = tf.constant(4.0,shape=(1,1),dtype=tf.float32)
# print(x)
x = tf.constant([[1,2,3],[4,5,6]])
# print(x)
x = tf.ones((3,3))
# print(x)
x =tf.eye(3)
# print(x)
x = tf.random.normal((3,3), mean=0, stddev=1)
# print(x)
x = tf.random.uniform((1,3), minval=0, maxval=1) #3 від 0 до 1   tf.Tensor([[0.7355474 0.8880601 0.8938205]], shape=(1, 3), dtype=float32)
# print(x)
x = tf.range(start=1, limit=10, delta=3)
# print(x)
x = tf.cast(x,dtype=tf.float64)
# print(x)

tf.Tensor([1. 4. 7.], shape=(3,), dtype=float64)


In [45]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])
z = tf.add(x,y)
# z = x + y
# print(z) #same as z = x +y

z = tf.subtract(x,y)
z = x-y
# print(z)

z = tf.tensordot(x,y,axes=1)# перемножити два тензори і числа додати
z = tf.reduce_sum(x*y,axis=0) #те саме
# print(z)
z = x ** 2 # кожне число в квадраті
print(z)



tf.Tensor([1 4 9], shape=(3,), dtype=int32)


In [ ]:
#indexing
x = tf.constant([0,1,1,2,3,2,3])
# print(x[:])#пповна копія масиву
# print(x[1:])#копія починаючи з першого
# print(x[1:3])#копія з першого по третє
# print(x[::2])#кожне друге

indeces = tf.constant([0, 3])
x_ind = tf.gather(x,indeces) # взяти такі то індекси
# print(x_ind)

x = tf.constant([[1,2],
                 [3,4],
                 [5,6]]) # 3,2 dimention

# print(x[0,:]) # [1,2] 
# print(x[0:2,:]) #[1,2][3,4]




tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)


In [73]:
#reshaping
x = tf.range(9)
# print(x)
x = tf.reshape(x,(3,3))
        #[[0 1 2]
        #  [3 4 5]
        #  [6 7 8]]
# print(x)
x = tf.transpose(x,perm=[1,0])
        # [[0 3 6]
        #  [1 4 7]
        #  [2 5 8]]
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
